
set -g @color_win_bg    "default"
set -g @color_win_fg    "default"
set -g @color_ui_bg     "default"
set -g @color_ui_fg     "default"
set -g @color_status_left_bg    "#ff00ff"
set -g @color_status_left_fg    "#ffff00"
set -g @color_status_right_bg   "#ff0000"
set -g @color_status_right_fg   "#00ffff"
set -g @color_accent1_bg  "#3a7591"
set -g @color_accent1_fg  "#b5c0c5"
set -g @color_accent2_bg  "#80be38"
set -g @color_accent2_fg  "#b8bdb3"
