

set -g @color_win_bg            "#fdf6e3"
set -g @color_win_fg            "#657b83"
set -g @color_ui_bg             "#eee8d5"
set -g @color_ui_fg             "#586e75"
set -g @color_status_left_bg    "default"
set -g @color_status_left_fg    "default"
set -g @color_status_right_bg   "default"
set -g @color_status_right_fg   "default"
set -g @color_accent1_bg        "#8338ec"
set -g @color_accent1_fg        "#eee8d5"
set -g @color_accent2_bg        "#ff006e"
set -g @color_accent2_fg        "#eee8d5"

# set -g window-style "bg=#{@color_win_bg}, fg=#{@color_win_fg}"
# set -g status-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}"

# set -g status-left-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}"

# set -g window-status-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}, bold"
# set -g window-status-current-style "bg=#{@color_accent_1}, fg=#{@color_ui_bg}, bold"
# set -g window-status-activity-style "bg=#{@color_accent_2}, fg=#{@color_ui_bg}, bold, blink"

# set -g status-right " #(uptime | sed 's|.*average: ||') #[bg=#{@color_accent_2}, fg=#{@color_ui_bg}, bold]#{?@win-monitor-status, #{@win-monitor-status} ,}#{@win-silence}#[bg=#{@color_accent_1}, fg=#{@color_ui_bg}, bold] %H:%M:%S "
