# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C): 2025 - 2026 - keiwop <keiwop.dev@gmail.com>


###############################################################################
### WINDOW ####################################################################
###############################################################################

set -g window-style "bg=#{@color_win_bg}, fg=#{@color_win_fg}"

set -g allow-rename off
set -g automatic-rename on
# set -g automatic-rename-format "#{b:pane_current_path}"
set -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"


###############################################################################
### STATUS BAR ################################################################
###############################################################################

set -g status-position bottom
set -g status-justify centre
set -g status-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}"


# Status bar - Left
set -g status-left " #(whoami)@#H "
set -g status-left-style "bg=#{@color_status_left_bg}, fg=#{@color_status_left_fg}"
set -g status-left-length 42


# Status bar - Center
# Window list
set -g window-status-format " #I #W#{?window_activity_flag,*,} "
set -g window-status-current-format " #I #W "

set -g window-status-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}, bold"
set -g window-status-current-style "bg=#{@color_accent1_bg}, fg=#{@color_accent1_fg}, bold"
set -g window-status-activity-style "bg=#{@color_accent2_bg}, fg=#{@color_accent2_fg}, bold, blink"


# Status bar - Right
set -g status-right " #(uptime | sed 's|.*average: ||') #[bg=#{@color_accent2_bg}, fg=#{@color_accent2_fg}, bold]#{?@win_monitor_status, #{@win_monitor_status} ,}#[bg=#{@color_accent1_bg}, fg=#{@color_accent1_fg}, bold] %H:%M:%S "
set -g status-right-style "bg=#{@color_status_right_bg}, fg=#{@color_status_right_fg}"
set -g status-right-length 80


###############################################################################
### MENU ######################################################################
###############################################################################

set -g menu-style "bg=#{@color_ui_bg}, fg=#{@color_ui_fg}"
set -g menu-selected-style "bg=#{@color_accent1_bg}, fg=#{@color_accent1_fg}"
set -g menu-border-style "bg=#{@color_ui_bg}, fg=#{@color_accent1_bg}"
